config/routes.rb
 Rails.application.routes.draw do
  resources :notebooks do
    resources :pages do
      resources :paragraphs
      resources :image_elements
      resources :checklists do
        resources :checklist_items
      end
    end
  end
  devise_for :users
  root to:  "home#index"
end

app/views/shared/_breadcrumbs.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb mb-5">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <% @breadcrumbs.each do |breadcrumb| %>
      <% if breadcrumb[:path].nil? %>
        <li class="breadcrumb-item active" aria-current="page">
          <%= breadcrumb[:label] %>
        </li>
      <% else %>
        <li class="breadcrumb-item">
          <%= link_to breadcrumb[:label], breadcrumb[:path] %>
        </li>
      <% end %>
    <% end %>
  </ol>
</nav>

app/views/shared/_navbar.html.erb
navbar
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">NotesApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My notebooks', notebooks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path,class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path,class: 'nav-link' %>

        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>